packages:
  - packages/*
  - apps/*

catalog:
  dayjs: ^1.11.13
  globals: ^15.14.0
  immer: ^10.1.1
  nanoid: ^5.0.9
  prettier: ^3.3.3
  rxjs: ^7.8.1
  typescript: 5.9.2
  typescript-eslint: ^8.18.2
  vite: ^5.4.11

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
