packages:
  - packages/*
  - apps/*

catalog:
  dayjs: ^1.11.13
  globals: 15.15.0
  immer: ^10.1.1
  nanoid: ^5.0.9
  prettier: ^3.3.3
  rxjs: 7.8.2
  typescript: 5.9.2
  typescript-eslint: 8.40.0
  vite: ^5.4.11

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
